server:
  port: 8080
  servlet:
    context-path: /abc

spring:
  conf:
    url: http://www.baidu.com
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: # 默认为空
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 200 # 连接最大数
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxl-job?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=converttonull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      max-active: 20
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      auto-commit-interval: 100
      auto-offset-reset: latest
      enable-auto-commit: true
      group-id: my_group_id
    topic: test_topic
#    template:
#      default-topic: test_topic
    listener:
      concurrency: 10
  httpclient:
    maxTotal: 100
    defaultMaxPerRoute: 20
    connectTimeout: 1000
    connectionRequestTimeout: 500
    socketTimeout: 10000
    staleConnectionCheckEnabled: true
# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  configLocation: classpath:mybatis-spring.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
