server:
  port: 8080
  servlet:
    context-path: /abc

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: # 默认为空
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 200 # 连接最大数
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 #连接池中的最小空闲连接
